export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DEACTIVATE: 'users.deactivate',

  RECORDS_READ: 'records.read',
  RECORDS_CREATE: 'records.create',
  RECORDS_UPDATE: 'records.update',
  RECORDS_DELETE: 'records.delete',

  DASHBOARD_READ: 'dashboard.read',
  DASHBOARD_ANALYTICS: 'dashboard.analytics',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  VIEWER: [
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.DASHBOARD_READ,
  ],
  ANALYST: [
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.DASHBOARD_ANALYTICS,
  ],
  ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.RECORDS_CREATE,
    PERMISSIONS.RECORDS_UPDATE,
    PERMISSIONS.RECORDS_DELETE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.DASHBOARD_ANALYTICS,
  ],
};